version: '3'

# the dockerfile here + a postgres db and minio

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - 9000:9000
    volumes:
      - ./minio:/data
    command: server /data

  app:
    build: .
    restart: always
    environment:
      POSTGRES_URL: postgres://postgres:postgres@db:5432/postgres
      NODE_ENV: production
      S3_ACCESS_KEY_ID: minio
      S3_SECRET_ACCESS_KEY: minio123
      S3_ENDPOINT: http://minio:9000
      S3_PUBLIC_URL: http://localhost:9000

    ports:
      - 3000:3000
    depends_on:
      - db
      - minio